Repository kalviumcommunity/S64_Samragyi_Capstone_SkinGenie, pull requests merged in 2025-05, with the labels that each got.

#45 Implemented authentication (3rd party - like google) in application
  backend/.gitignore
  backend/config/passport.js
  backend/middleware/authMiddleware.js
  backend/models/user.js
  backend/package.json
  backend/routes/authRoutes.js
  backend/server.js
  frontend/.env
  frontend/src/api.js
  frontend/src/axios.config.js
  frontend/src/context/AuthContext.js
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/SignupPage.jsx
Labels: Review effort 4/5

#46 Upload image
  backend/package.json
  backend/routes/upload.js
  backend/server.js
  backend/uploads/1746641866427-694286589.png
  backend/uploads/1746643220916-333157005.png
  backend/uploads/1746643526867-103975058.png
  frontend/.env
  frontend/.gitignore
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/pages/RoutinePage.jsx
Labels: Review effort 2/5

#47 Updated Login Signup Page
  backend/controllers/userController.js
  backend/uploads/1746644118684-992419121.png
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/SignupPage.jsx
Labels: Review effort 2/5

#48 Implementing 'update' and 'delete' an entity in React app
  backend/controllers/commentController.js
  backend/routes/commentRoutes.js
  frontend/src/api.js
  frontend/src/components/AddCommentForm.jsx
  frontend/src/components/CommentsList.jsx
  frontend/src/context/AuthContext.jsx
  frontend/src/pages/ProductReview.jsx
Labels: Review effort 3/5

#49 Updated bruno/API templates in application repo
  backend/controllers/commentController.js
  docs/Bruno.API/Comment Routes/Get Comment.bru
  docs/Bruno.API/Comment Routes/Post Comment.bru
  docs/Bruno.API/Product Routes/Create Product.bru
  docs/Bruno.API/Product Routes/Get Product.bru
  docs/Bruno.API/Routine Routes/Get Routine.bru
  docs/Bruno.API/User Routes/Get All Users.bru
  docs/Bruno.API/User Routes/Get Single User.bru
  docs/Bruno.API/User Routes/Login.bru
  docs/Bruno.API/User Routes/Signup.bru
  docs/Bruno.API/bruno.json
  frontend/src/api.js
Labels: Review effort 2/5

#51 Added frontend deployment link in cors origin
  backend/server.js
  frontend/src/axios.config.js
Labels: Review effort 1/5

#52 Improved functionality
  backend/controllers/commentController.js
  backend/middleware/authMiddleware.js
  backend/routes/authRoutes.js
  backend/server.js
  frontend/src/api.js
  frontend/src/components/CommentsList.jsx
  frontend/src/styles/LoginPage.css
  frontend/src/styles/QuizPage.css
  frontend/src/styles/SignupPage.css
Labels: Review effort 3/5

#53 Used a testing framework (JEST) in application
  backend/__tests__/authMiddleware.test.js
  backend/__tests__/commentController.test.js
  backend/package.json
  frontend/.babelrc
  frontend/__mocks__/fileMock.js
  frontend/__mocks__/styleMock.js
  frontend/babel.config.js
  frontend/jest.setup.js
  frontend/package.json
  frontend/src/components/__tests__/AddCommentForm.test.jsx
  frontend/src/components/__tests__/CommentsList.test.jsx
Labels: Review effort 2/5

#55 OTP provider
  backend/models/user.js
  backend/routes/passwordResetRoutes.js
  backend/server.js
  frontend/src/App.jsx
  frontend/src/pages/ForgotPasswordPage.jsx
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/ResetPasswordPage.jsx
  frontend/src/styles/AuthForms.css
Labels: Review effort 3/5

#56 API integration (OTP provider)
  backend/controllers/passwordResetController.js
  backend/models/user.js
  backend/routes/passwordResetRoutes.js
  backend/server.js
  backend/utils/emailService.js
  backend/utils/otpUtils.js
  frontend/src/pages/ForgotPasswordPage.jsx
  frontend/src/pages/ResetPasswordPage.jsx
  frontend/src/styles/AuthForms.css
Labels: Review effort 3/5

#57 Enabled Dark Mode for Better UI and UX
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/DarkModeToggle.jsx
  frontend/src/components/Navbar.jsx
  frontend/src/context/ThemeContext.jsx
  frontend/src/main.jsx
  frontend/src/pages/RoutinePage.jsx
  frontend/src/styles/DarkModeToggle.css
  frontend/src/styles/HomePage.css
  frontend/src/styles/Navbar.css
  frontend/src/styles/RoutinePage.css
Labels: Review effort 3/5

#58 Added streak-functionality in routine page
  backend/__tests__/authMiddleware.test.js
  backend/controllers/routineTrackerController.js
  backend/middleware/authMiddleware.js
  backend/models/routineTracker.js
  backend/routes/commentRoutes.js
  backend/routes/routineRoutes.js
  backend/routes/routineTrackerRoutes.js
  backend/routes/userRoutes.js
  backend/server.js
  frontend/src/pages/LoginPage.jsx
  frontend/src/pages/RoutinePage.jsx
  frontend/src/styles/RoutinePage.css
Labels: Review effort 3/5

#59 Added Skincare Tip of the day feature
  frontend/src/components/SkincareTip.jsx
  frontend/src/pages/RoutinePage.jsx
  frontend/src/styles/SkincareTip.css
Labels: Review effort 3/5
